/*
 * Alert Manager API Spec
 *
 * Alert Manager API spec. This spec represents the Alert Management service whose current objective is to prioritize the alerts based upon context.  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@dassana.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Rule : IEquatable<Rule>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Operator
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum OperatorEnum
        {
            /// <summary>
            /// Enum AndEnum for and
            /// </summary>
            [EnumMember(Value = "and")]
            AndEnum = 0,
            /// <summary>
            /// Enum OrEnum for or
            /// </summary>
            [EnumMember(Value = "or")]
            OrEnum = 1        }

        /// <summary>
        /// Gets or Sets Operator
        /// </summary>
        [Required]
        [DataMember(Name="operator")]
        public OperatorEnum? Operator { get; set; }

        /// <summary>
        /// Gets or Sets Conditions
        /// </summary>
        [Required]
        [DataMember(Name="conditions")]
        public List<Condition> Conditions { get; set; }

        /// <summary>
        /// Gets or Sets RiskRank
        /// </summary>
        [DataMember(Name="riskRank")]
        public RiskRank RiskRank { get; set; }

        /// <summary>
        /// this is set to true if the rule was matched
        /// </summary>
        /// <value>this is set to true if the rule was matched</value>
        [DataMember(Name="matched")]
        public bool? Matched { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Rule {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Conditions: ").Append(Conditions).Append("\n");
            sb.Append("  RiskRank: ").Append(RiskRank).Append("\n");
            sb.Append("  Matched: ").Append(Matched).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Rule)obj);
        }

        /// <summary>
        /// Returns true if Rule instances are equal
        /// </summary>
        /// <param name="other">Instance of Rule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Rule other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Operator == other.Operator ||
                    Operator != null &&
                    Operator.Equals(other.Operator)
                ) && 
                (
                    Conditions == other.Conditions ||
                    Conditions != null &&
                    Conditions.SequenceEqual(other.Conditions)
                ) && 
                (
                    RiskRank == other.RiskRank ||
                    RiskRank != null &&
                    RiskRank.Equals(other.RiskRank)
                ) && 
                (
                    Matched == other.Matched ||
                    Matched != null &&
                    Matched.Equals(other.Matched)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Operator != null)
                    hashCode = hashCode * 59 + Operator.GetHashCode();
                    if (Conditions != null)
                    hashCode = hashCode * 59 + Conditions.GetHashCode();
                    if (RiskRank != null)
                    hashCode = hashCode * 59 + RiskRank.GetHashCode();
                    if (Matched != null)
                    hashCode = hashCode * 59 + Matched.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Rule left, Rule right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Rule left, Rule right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
